### PR TITLE
Try: Use luminance of color to check for "white" background

### LINKED ISSUE #873: With an off-white page background, text focus styles are hard to see
**Describe the bug**

If the page background is set to an off-white color (I used `#f9f9f9` in my testing), the focus styles for buttons and links is hard to see: 

**Expected behavior**

I expected something more akin to the dark focus background used when the background is set to white. 

**Screenshots**

Navigation:
Screen Shot 2020-11-23 at 3 11 48 PM

Post title:
Screen Shot 2020-11-23 at 3 14 48 PM

Post meta:
Screen Shot 2020-11-23 at 3 14 55 PM

### PR DESCRIPTION
**Pull request by ryelle**
This PR is an alternate solution to #873 (other solution is #877). This expands what colors are considered "white" for the higher-contrast black focus state.

This addresses @melchoyce's comment,

> Is there any way to keep the white focus styles in the colorful schemes?

Fixes #873

## Summary
Instead of checking for exactly `#ffffff`, this checks whether the luminance of the color is greater than 225. This ensures most of the default background colors have a white focus color, while custom light-grey (like `#eee`) will trigger the black focus style. The default yellow color also has a high-enough luminance that it triggers the black focus.

## Relevant technical choices:

In the interest of not changing the CSS, I'm sticking with the class name `has-background-white`; I'm on the fence about whether it's too unclear though.

## Test instructions

This PR can be tested by following these steps:
1. Play with a number of background colors. The focus style should be visible.

## Screenshots

I've got a lot of screenshots, each one the same page with the title focused.

<details>
<summary>View screenshots</summary>

black

grey

blue

red

yellow

white

Dark Mode:
dark-mode

Custom color: `#eeeeee`
custom-eee

Custom color: `#eef4d7`
custom-eef4d7

</details>

## Quality assurance
* [x] I have thought about any security implications this code might add.
* [x] I have checked that this code doesn't impact performance (greatly).
* [x] I have tested this code to the best of my abilities
* [x] I have checked that this code does not affect the accessibility negatively

### CODE REVIEW

**Review by kjellr — APPROVED** [review]
This works well in my testing! Fixes https://github.com/WordPress/twentytwentyone/issues/873, while also keeping the white hover color in the theme's suggested color schemes as @melchoyce requested in https://github.com/WordPress/twentytwentyone/pull/877#issuecomment-733081496.

**Comment by carolinan** [comment]
I understand why we want to keep the white background, but it turns out it is not enough on it's own, added the contrast ratios here:
https://github.com/WordPress/twentytwentyone/issues/873#issuecomment-733451555

For some links the fix is very easy, change or remove the style of the underline. With a text decoration change that not relies on color, we can use the white.

File: assets/js/customize-preview.js [hunk 1]
```diff
@@ -15,17 +15,21 @@
 			if ( isDark ) {
 				document.body.classList.add( 'is-dark-theme' );
 				document.documentElement.classList.add( 'is-dark-theme' );
+				document.body.classList.remove( 'is-light-theme' );
```
Comment (carolinan) [inline assets/js/customize-preview.js:18]: We no longer need the is-light-theme class here, unless we want to add it for other people to use?

Comment (aristath) [reply assets/js/customize-preview.js:18]: Yeah, I'd rather keep it even if we don't use it... It will make customizations easier for those who will want to write custom css (`body.is-light-theme` is easier than `body:not(.is-dark-theme)`)

**Review by aristath — APPROVED** [review]
LGTM :+1:
